services:
  - type: web
    name: Medicare
    runtime: node
    rootDir: .
    buildCommand: npm install --include=dev --prefix backend && npm install --prefix frontend && npm run build --prefix backend && npm run build --prefix frontend
    startCommand: node backend/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGHOST
        value: dpg-da3f642jnfac73ccqnig-a.ohio-postgres.render.com
      - key: PGPORT
        value: "5432"
      - key: PGUSER
        value: medicare
      - key: PGPASSWORD
        value: dJb0LB3hNpk5BeEneksdrmT9Nf01Y6CY
      - key: PGDATABASE
        value: medicare_mmiw
    disk:
      name: medicare-uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1
